name: Manual tracking automation

on:
  workflow_dispatch:
    inputs:
      script:
        description: Script's handler you wanna run tracking automation on
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: cachix/install-nix-action@v31.10.6

      - name: Clone nixpkgs (blobless)
        run: |
          git clone --no-checkout --filter=blob:none --origin upstream \
            --branch master --single-branch \
            https://github.com/NixOS/nixpkgs.git nixpkgs

      - name: Run tracking automation for ${{ inputs.script }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCRIPT: ${{ inputs.script }}
        run: |
          nix run ".#$SCRIPT.tracking-automation.run" -- \
            --worktree "$GITHUB_WORKSPACE/nixpkgs" \
            --out artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: tracking-${{ inputs.script }}
          path: artifacts
