name: Manual script run

on:
  workflow_dispatch:
    inputs:
      script:
        description: Flake app to run (you probably wants to run a script, dont you?)
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: cachix/install-nix-action@v31.10.6

      - name: Get latest nixpkgs's master rev
        id: rev
        run: |
          rev=$(git ls-remote https://github.com/NixOS/nixpkgs.git master | cut -f1)
          echo "rev=$rev" | tee -a "$GITHUB_OUTPUT"

      - name: Run ${{ inputs.script }}
        env:
          SCRIPT: ${{ inputs.script }}
        run: |
          nix run ".#$SCRIPT" \
            --override-input subject-nixpkgs github:NixOS/nixpkgs/${{ steps.rev.outputs.rev }}
