name: Manual script run

on:
  workflow_dispatch:
    inputs:
      script:
        description: Flake app to run (you probably wants to run a script, dont you?)
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: cachix/install-nix-action@v31.10.6

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Run ${{ inputs.script }}
        env:
          SCRIPT: ${{ inputs.script }}
        run: nix run ".#$SCRIPT"
